### ISSUE TITLE
How to expand abbreviation with prefix semicolon?

### ISSUE THREAD

**Issue by snowman** [condy0919/emacs-newbie#4]
Like the given example from you:

https://github.com/condy0919/emacs-newbie/blob/bbdf947cb210f5d5ce11fd9781dd1a6f8aa3176b/introduction-to-builtin-modes.md#L576-L578

I could not expand `;license` followed by space, but define abbreviation with follow:
```elisp
(define-abbrev emacs-lisp-mode-abbrev-table "2license" "" 'tempo-template-license) 
```

then expand `2license` by `2license` followed by space, it expands.

**Comment by condy0919** [comment]
Good catch!
`abbrev-expand` expands the WORD in current syntax table, while `;license` consists of `;` and `license`.

**Comment by condy0919** [comment]
Fixed by https://github.com/condy0919/emacs-newbie/commit/0829a4303d0ee1602a38bc8613e83abcf2afd882
