### ISSUE TITLE
Question: do you get an error when killing a term buffer?

### ISSUE THREAD

**Issue by AmaiKinono** [condy0919/emacs-newbie#7]
Here's a test:

- `$ emacs -Q`
- `M-x ansi-term`, `RET`
- `C-x k` to kill the term buffer
- There's an error: `Error in process filter: Selecting deleted buffer`. Emacs will freeze for a few seconds and you can't do anything during the period.

I'm on Emacs 27.1, GNU/Linux. Maybe I should fill a bug report to GNU Emacs, but I just feel suspicious that this happens in vanilla Emacs.

**Comment by AmaiKinono** [comment]
Oh I didn't notice this repo has opened "Discussions". Please transfer this issue to a discussion if you think it's appropriate.

**Comment by condy0919** [comment]
can't reproduce on Emacs 28, maybe an Emacs bug

**Comment by AmaiKinono** [comment]
Thanks!

I reproduced it in Emacs 28, so I filled a [bug report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=46323). And they [fixed it 2 hours ago](https://github.com/emacs-mirror/emacs/commit/9730575f3a2599be0a4f9c3d1ef5321bf1294e93) ;)
